import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>Navigation Section</nav>
        {children}
        <footer>Footer Section</footer>
      </body>
    </html>
  );
}
